"""Добавление столбика имени для чата

Revision ID: eea206bf7b52
Revises: 
Create Date: 2024-05-02 01:22:39.658984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "eea206bf7b52"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("team_user", schema=None) as batch_op:
        batch_op.drop_constraint("fk_sender_id", type_="foreignkey")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("team_user", schema=None) as batch_op:
        batch_op.create_foreign_key("fk_sender_id", "user", ["username"], ["id"])

    # ### end Alembic commands ###
